kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: rhdh
  labels:
    app.kubernetes.io/component: backstage
    app.kubernetes.io/instance: rhdh-loadtests-17
    app.kubernetes.io/name: developer-hub
spec:
  to:
    kind: Service
    name: rhdh-loadtests-17-developer-hub
    weight: 100
